{application,aten,
             [{id, "v3.13.3-56-ged42cd1"},
              {description,"Erlang node failure detector"},
              {vsn,"0.6.0"},
              {licenses,["Apache","MPL"]},
              {links,[{"github","https://github.com/rabbitmq/aten"}]},
              {modules, ['aten','aten_app','aten_detect','aten_detector','aten_emitter','aten_sink','aten_sup']},
              {registered,[aten_sup]},
              {applications,[kernel,stdlib,sasl,crypto]},
              {mod,{aten_app,[]}},
              {env,[{poll_interval,1000},
                    {scaling_factor,1.5},
                    {heartbeat_interval,100},
                    {detection_threshold,0.99}]}]}.
